#!/bin/sh
export QT_QPA_PLATFORM=xcb
export QT_PLUGIN_PATH="$SNAP/usr/lib/x86_64-linux-gnu/qt6/plugins:${QT_PLUGIN_PATH:-}"
export PYTHONPATH="$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.12:$SNAP/usr/lib/python3.12/dist-packages:${PYTHONPATH:-}"
export LD_LIBRARY_PATH="$SNAP/usr/lib/x86_64-linux-gnu:$SNAP/usr/lib/x86_64-linux-gnu/qt6/plugins/platforms:${LD_LIBRARY_PATH:-}"
export GI_TYPELIB_PATH="$SNAP/usr/lib/x86_64-linux-gnu/girepository-1.0:${GI_TYPELIB_PATH:-}"
exec /usr/bin/python3.12 "$SNAP/inetshot.py" "$@"
